services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: 'redis:latest'
    volumes:
      - 'redis:/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  web:
    container_name: compress--web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    environment:
      - REDIS_URL=redis://redis:6379/1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/compress
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - smtp4dev
  workers:
    depends_on:
      - db
      - redis
      - smtp4dev
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml -e ${RAILS_ENV}
    volumes:
      - '.:/compress'
    environment:
      - REDIS_URL=redis://redis:6379/1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '5001:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev:/data


volumes:
  redis:
  postgres:
  smtp4dev: