services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: 'redis:latest'
    volumes:
      - 'redis:/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  web:
    container_name: compress--web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/compress
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  workers:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/compress'
      - '/compress/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL=redis://redis:6379/3


volumes:
  redis:
  postgres: